Repository jenkinsci/junit-sql-storage-plugin, pull requests merged in 2024-06, with the labels that each got.

#413 Add caching, tracing, logging, and batching to the plugin
  Dockerfile
  README.md
  deploy.sh
  docker-compose.yaml
  images/install-junit-sql-storage-plugin.png
  images/junit-sql-database-config.png
  jenkins-config.yaml
  pom.xml
  src/main/java/io/jenkins/plugins/junit/storage/database/DatabaseTestResultStorage.java
  src/main/java/io/jenkins/plugins/junit/storage/database/TestResultCleanupListener.java
  src/test/java/io/jenkins/plugins/junit/storage/database/DatabaseTestResultStorageTest.java
Labels: enhancement

#417 Bump baseline
  pom.xml
Labels: developer

#418 Enable Jenkins Security Scan
  .github/workflows/jenkins-security-scan.yml
Labels: chore
